In [6]:
#t1
#输入与输出
# name = input('What is your name?')
sum = 100 + 100
# print('hello, %s' %name)
# print('sum = %d' %sum)
print('{}'.format(sum))

200


In [2]:
#format输出方法的其他的使用方法
print('{a}天气晴朗'.format(a='今天'))

grade = {'I' : '拦路雨', '状态': '写博客'}
print('{I}比较无聊，在{状态}'.format(**grade))#字典前加上**

今天天气晴朗
拦路雨比较无聊，在写博客


In [3]:
a = 1
print('{}'.format(a))

1


In [7]:
s1 = {'subject':'Mike','verb-ing':'running','adv':'for a long time'}
print('His name is {subject}. He likes {verb-ing}, and he does it {adv}'.format(**s1))

His name is Mike. He likes running, and he does it for a long time


In [ ]:
#t2
# 条件判断
score = int(input('what is the score?'))
if score >= 90:
    print('Excellent!')
elif score < 60:
    print('Failed')
else:
    print('Good job!')

In [ ]:
#t3
# for循环
sum1 = 0
for num in range(11):
    sum1 += num
print(sum1)  

# while循环
sum2 = 0
num = 1
while num < 11:
    sum2 += num
    num += 1
print(sum2)

In [9]:
#while循环与条件判断结合应用
#猜年龄
yueer = 18
count = 0
while count < 3:
     yueerage = int(input('悦儿多大呢：'))
     if yueerage == yueer:
         print('恭喜你猜中了。')
         break
     elif yueerage > yueer:
         print('你猜得太大了。')
     elif yueerage < yueer:
         print('再大一点')
     count += 1
     if count ==3:
         count_jixu = input('继续Y，不继续N：')
         if count_jixu == 'Y':
             count = 0
         elif count_jixu == 'N':
             count = 3
else:
     print("fuck off")

悦儿多大呢： 12


再大一点


悦儿多大呢： 18


恭喜你猜中了。


In [ ]:
#t4
#列表
lists = ['zhangfei','guanyu','liubei']
#append()
lists.append('dianwei')
print(lists)
print(len(lists))
#insert an element at a certain place
lists.insert(0,'diaochan')
print(lists)
#delete the last element
lists.pop()
print(lists)

列表删除元素的方法
a.pop(index):删除列表a中index处的值,并且返回这个值.
del(a[index]):删除列表a中index处的值,无返回值. del中的index可以是切片,所以可以实现批量删除.
a.remove(value):删除列表a中第一个等于value的值,无返回.
#* 列表批量删除时可以选择倒叙再遍历的方法，否则会存在删除不全的状态。

In [19]:
a=[1,5,4,5,3,5,7,9]
#print(a.pop(1))
#del(a[0:2])
#a.remove(5)
print(a)

[1, 4, 5, 3, 5, 7, 9]


In [ ]:
#t5
#元组
tuples = ('zhangfei',65)
print(tuples[0])

#返回字典key组成的tuple
print(tuple({'zhangfei':88,'diaochan':33}))

# 列表转化为元组
temp_list = [123, 'zhangfei', 'guanyu', 'liubei'];
temp_tuple = tuple(temp_list)
print(temp_tuple)


In [ ]:
#t6
#字典
#定义一个dictionary
score = {'guanyu':96,'zhangfei':95}

#添加一个元素
score['zhaoyun'] = 98
print(score)

#删除一个元素
score.pop('zhangfei')
print(score)

#查看key是否存在
print('zhangfei' in score)

#查看一个key对应的值
print(score.get('zhangfei'))
print(score.get('dianwei',99))
print(score)

In [ ]:
#t7
#集合
s = set(['dianwei','diaochan','zhaoyun'])
s.add('liubei')
print(s)
s.remove('diaochan')
print(s)
print('diaochan' in s)

#set有一个简单的应用，set（列表） 可以进行列表去重

In [ ]:
#t8
#numpy的使用
import numpy as np

#ndarray的使用
def work1():
    a = np.array([1,2,3])
    b = np.array([[1,2,3], [4,5,6], [7,8,9]])
    b[1,1] = 10
    print(a.shape)
    print(b.shape)
    print(a.dtype)
    print(b)
    
#结构化数组的使用
def work2():
    persontype = np.dtype({'names':['name','age','chinese','math','english'], 'formats':['S32','i', 'i', 'i', 'f']})
    peoples = np.array([("ZhangFei",32,75,100, 90),("GuanYu",24,85,96,88.5),("ZhaoYun",28,85,92,96.5),("HuangZhong",29,65,85,100)],\
                       dtype=persontype)
    ages = peoples['age']
    chineses = peoples['chinese']
    maths = peoples['math']
    englishs = peoples['english']
    print(ages, chineses, maths, englishs)
    print(np.mean(ages))
    print(np.mean(chineses))
    print(np.mean(maths))
    print(np.mean(englishs))


work1()
print('--------------')
work2()

In [ ]:
#t9
# 连续数组的创建：arange 或 linspace
import numpy as np
x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)
print('x1=', x1)
print('x2=', x2)

print(np.add(x1,x2))
print(np.subtract(x1,x2))
print(np.multiply(x1,x2))
print(np.divide(x1,x2))
print(np.power(x1,x2))
print(np.remainder(x1,x2))

In [52]:
#t10
# numpy中统计函数的使用
import numpy as np
# 最大、最小值
def work1():
    a = np.array([[1,2,3], [4,5,6], [7,8,9]])
    print(np.min(a))
    print(np.min(a,0))
    print(np.min(a,1))
    print(np.max(a))
    print(np.max(a,0))
    print(np.max(a,1))

# 统计百分位数
def work2():
	a = np.array([[1,2,3], [4,5,6], [7,8,9]])
	print(np.percentile(a, 50))
	print(np.percentile(a, 50, axis=0))
	print(np.percentile(a, 50, axis=1))

# 中位数、平均数
def work3():
	a = np.array([[1,2,3], [4,5,6], [7,8,9]])
	#求中位数
	print(np.median(a))
	print(np.median(a, axis=0))
	print(np.median(a, axis=1))
	#求平均数
	print(np.mean(a))
	print(np.mean(a, axis=0))
	print(np.mean(a, axis=1))

# 加权平均值
def work4():
	a = np.array([1,2,3,4])
	weights = np.array([1,2,3,4])
	print(np.average(a))
	print(np.average(a,weights=weights))

# 标准差、方差
def work5():
	a = np.array([1,2,3,4])
	print(np.std(a))
	print(np.var(a))

# 对数组进行排序
def work6():
	a = np.array([[4,3,2],[2,4,1]])
	print(np.sort(a))
	print(np.sort(a, axis=None))
	print(np.sort(a, axis=0))
	print(np.sort(a, axis=1))
	print(type(a))
	
# 对数组进行排序
def work7():
	# 使用List进行排序
	a = [4,3,2,2,4,1]
	print(type(a))
	a.sort()
	print(a)
	a.sort(reverse=True)
	print(a)

print('min and max')
work1()
print('percentile')
work2()
print('mean and median')
work3()
print('weighted mean')
work4()
print('stdev and variance')
work5()
print('sort1')
work6()
print('sort2')
work7()

min and max
1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]
percentile
5.0
[4. 5. 6.]
[2. 5. 8.]
mean and median
5.0
[4. 5. 6.]
[2. 5. 8.]
5.0
[4. 5. 6.]
[2. 5. 8.]
weighted mean
2.5
3.0
stdev and variance
1.118033988749895
1.25
sort1
[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]
<class 'numpy.ndarray'>
sort2
<class 'list'>
[1, 2, 2, 3, 4, 4]
[4, 4, 3, 2, 2, 1]


In [ ]:
#action2
#求2+4+6+8+...+100的求和
sum = 0
for i in range(2,101):
    sum += i
print(sum)

In [ ]:
#这道题应该是没仔细看题，要求100内偶数和
sum = 0
for i in range(2, 101, 2):
    print(i)
    sum += i
print(sum)

In [20]:
#action3
#我的版本
#统计全班的成绩
import numpy as np
persontype = np.dtype({'names':['name','Chinese','Math','English'], 'formats':['S32', 'i', 'i', 'i']})
scores = np.array([('Zhangfei',68,65,30),('Guanyu',95,76,98),('Liubei',98,86,88),('Dianwei',90,88,77),('Xuzhu',80,90,90)], dtype = persontype)
Chineses = scores['Chinese']
Maths = scores['Math']
Englishs = scores['English']
names = scores['name']
print('Min Chinese:', Chineses.min())
print('Min English:', Englishs.min())
print('Min Math:', Maths.min())

print('Mean Chinese:', Chineses.mean())
print('Mean English:', Englishs.mean())
print('Mean Math:', Maths.mean())

print('std Math:', np.std(Maths))

total = []
for i in range(5):
    t = scores[i][1]+scores[i][2]+scores[i][3]
    total.append(t)
total = np.array(total)
s0 = np.vstack((names,total))
s0 = s0.T
print(s0)
np.sort(s0, axis = 0)

Min Chinese: 68
Min English: 30
Min Math: 65
Mean Chinese: 86.2
Mean English: 76.6
Mean Math: 81.0
std Math: 9.338094023943002
[[b'Zhangfei' b'163']
 [b'Guanyu' b'269']
 [b'Liubei' b'272']
 [b'Dianwei' b'255']
 [b'Xuzhu' b'260']]


array([[b'Dianwei', b'163'],
       [b'Guanyu', b'255'],
       [b'Liubei', b'260'],
       [b'Xuzhu', b'269'],
       [b'Zhangfei', b'272']], dtype='|S32')

In [22]:
#助教版本

import numpy as np

# 1、先定义一个人物类
persontype = np.dtype({
    'names': ['name', 'chinese', 'math', 'english'],
    'formats': ['S32', 'i', 'i', 'i']
})
# 2、将数据加载
peoples = np.array([("zhangfei", 68, 65, 30), ("guanyu", 95, 76, 98),
                    ("liubei", 98, 86, 88), ("dianwei", 90, 88, 77), ("xuchu", 80, 90, 90)],
                   dtype=persontype)
# 3、统计单科成绩
chineses = peoples[:]['chinese']
englishs = peoples[:]['english']
maths = peoples[:]['math']
# 平均成绩
print('mean', np.mean(chineses))
print('mean', np.mean(englishs))
print('mean', np.mean(maths))
# 输出最小值和最大值
print('min', np.amin(chineses))
print(np.amin(englishs))
print(np.amin(maths))
print(np.amax(chineses))
print(np.amax(englishs))
print(np.amax(maths))
# 计算方差和标准差
stdchinese = np.array(chineses)
print(np.std(stdchinese))
print(np.var(stdchinese))
stdenglish = np.array(englishs)
print(np.std(stdenglish))
print(np.var(stdenglish))
stdmath = np.array(maths)
print('std math: ',np.std(stdmath))
print(np.var(stdmath))
# 排序
# ①所有成绩
a = np.array([chineses, englishs, maths])
print(np.sort(a))
# ②按照三科成绩之和降序排列
# 用sorted函数进行排序
ranking = sorted(peoples, key=lambda x: x[1] + x[2] + x[3], reverse=True)
print(ranking)


mean 86.2
mean 76.6
mean 81.0
min 68
30
65
98
98
90
10.961751684835777
120.16
24.24541193710678
587.8399999999999
std math:  9.338094023943002
87.2
[[68 80 90 95 98]
 [30 77 88 90 98]
 [65 76 86 88 90]]
[(b'liubei', 98, 86, 88), (b'guanyu', 95, 76, 98), (b'xuchu', 80, 90, 90), (b'dianwei', 90, 88, 77), (b'zhangfei', 68, 65, 30)]
